services:
  - type: web
    name: alquidata-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn run:app --host 0.0.0.0 --port 8000
    envVars:
      - key: APP_NAME
        value: Alquidata
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        value: 8f6c46c6e022408f90fce3e2c94f0f54c2cfe2b234bd2b64cf7b9e6d3141f417
      - key: CLAUDE_API_KEY
        value: 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
      - key: N8N_API_URL
        value: http://localhost:5678/api/v1
      - fromGroup: alquidata-db-env

databases:
  - name: alquidata-db
    plan: free
    databaseName: alquidata
    user: alquidata_user
    envVarGroups:
      - name: alquidata-db-env

